Check this puppy out
litehed/FTC-Goal-2020 pull request #7
Opened 2020-11-12 21:14 UTC by liteheded

2020-11-12 21:17 UTC, liteheded commented
Wait shoot I messed some stuff up I redact that Check this puppy out statement

2020-11-12 21:19 UTC, JIceberg commented
Too late

2020-11-12 21:49 UTC, JIceberg requested changes

2020-11-12 21:49 UTC, JIceberg commented on .github/workflows/gradle.yml
> +    branches: '**'
PagChomp

2020-11-12 21:49 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeleOpMain.java
> +        pickup = new MotorEx(hardwareMap, "wobble", Motor.GoBILDA.BARE);
Why exactly is the pickup motor bare?

2020-11-12 21:49 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/IntakeSystem.java
> +    public boolean intakeActive = false;
Make this private.

2020-11-12 21:49 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/IntakeSystem.java
> +
Add two methods. One called `toggle()` and one called `active()`:
```java
public boolean active() {
    return intakeActive;
}

public void toggle() {
    intakeActive = !intakeActive;
}
```

2020-11-12 21:49 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeleOpMain.java
> +                .whenPressed(startIntakeCommand);
I don't think this works. I'd recommend using one singular definition for the button with a `toggleWhenPressed` binding. My suggestion is this:
```java
toggleIntake = new GamepadButton(m_driverOp, GamepadKeys.Button.X)
        .whenPressed(new ConditionalCommand(startIntakeCommand, stopIntakeCommand, intakeSystem::active))
        .toggleWhenPressed(new InstantCommand(intakeSystem::toggle));
```
Refer to my comment in IntakeSubsystem for more information.

2020-11-12 21:49 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/WobbleSystem.java
> +        //I need to test stuff out so Im leaving this unfinished for now
Make this `//TODO: testing`

2020-11-12 21:55 UTC, JIceberg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/IntakeSystem.java
> +    public boolean intakeActive = false;
Also, instantiate it as true.

2020-11-13 00:52 UTC, liteheded commented
Lol neither of us noticed that I never declared the motor for the intake

2020-11-13 00:55 UTC, JIceberg commented
You never answered when I asked why the wobble goal motor is bare.

2020-11-13 00:56 UTC, liteheded commented
> You never answered when I asked why the wobble goal motor is bare.

Oh yeah I don't know what it's supposed to be and I was using a 6k for testing which is also why I don't have code in the spin me right round baby

2020-11-13 00:56 UTC, JIceberg commented
Ah okay. We'll leave it then. Ask Aiden when you get the chance.

2020-11-13 01:00 UTC, JIceberg approved these changes
Nice.

2020-11-13 01:00 UTC, merged